services:
  pocketbase:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_data:/pb/pb_data
      - ./backend/pb_migrations:/pb/pb_migrations
      - ./backend/pb_hooks:/pb/pb_hooks
    develop:
      watch:
        - action: rebuild
          path: backend/pb_migrations
        - action: rebuild
          path: backend/pb_hooks
        - action: rebuild
          path: backend/Dockerfile.dev
